# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/aasm/all/aasm.rbi
#
# aasm-5.5.0

module AASM
end
module AASM::Persistence
end
module AASM::Persistence::ActiveRecordPersistence
end
module AASM::Persistence::ActiveRecordPersistence::ClassMethods
end
module AASM::Persistence::ActiveRecordPersistence::InstanceMethods
end
