# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: false
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/activemodel/all/activemodel.rbi
#
# activemodel-7.1.3.2

module ActiveModel
end
module ActiveModel::Model
  extend ActiveSupport::Concern
  include ActiveModel::API
  include ActiveModel::Access
end
