# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: false
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/actionpack/all/actionpack.rbi
#
# actionpack-7.1.3.2

module ActionDispatch
end
module ActionDispatch::Integration
end
module ActionDispatch::Integration::RequestHelpers
end
class ActionDispatch::Integration::Session
  extend ActionDispatch::Assertions::RoutingAssertions::ClassMethods
  include ActionDispatch::Assertions::RoutingAssertions
  include ActionDispatch::Routing::UrlFor
  include ActionDispatch::TestProcess
  include Minitest::Assertions
end
module ActionDispatch::Integration::Runner
  extend ActionDispatch::Assertions::RoutingAssertions::ClassMethods
  include ActionDispatch::Assertions
  include ActionDispatch::Assertions::RoutingAssertions
end
class ActionDispatch::IntegrationTest < ActiveSupport::TestCase
  extend ActionDispatch::IntegrationTest::Behavior::ClassMethods
  include ActionDispatch::IntegrationTest::Behavior
  include ActionDispatch::IntegrationTest::UrlOptions
  include ActionDispatch::Routing::UrlFor
  include ActionDispatch::TestProcess::FixtureFile
  include ActionMailer::TestCase::ClearTestDeliveries
  include ActionMailer::TestHelper
  include ActiveJob::TestHelper
  include Turbo::TestAssertions::IntegrationTestAssertions
end
module ActionDispatch::IntegrationTest::UrlOptions
  extend ActiveSupport::Concern
end
module ActionDispatch::IntegrationTest::Behavior
  extend ActiveSupport::Concern
  include ActionController::TemplateAssertions
  include ActionDispatch::Integration::Runner
end
module ActionDispatch::IntegrationTest::Behavior::ClassMethods
end
class ActionDispatch::RequestEncoder
end
class ActionDispatch::RequestEncoder::TurboStreamEncoder < ActionDispatch::RequestEncoder::IdentityEncoder
end
