# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: false
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/activejob/all/activejob.rbi
#
# activejob-7.1.3.2

module ActiveJob
end
module ActiveJob::TestHelper
  include ActiveSupport::Testing::Assertions
end
module ActiveJob::TestHelper::TestQueueAdapter
  extend ActiveSupport::Concern
end
module ActiveJob::TestHelper::TestQueueAdapter::ClassMethods
end
class ActiveJob::Base
  extend ActiveJob::TestHelper::TestQueueAdapter::ClassMethods
  include ActiveJob::TestHelper::TestQueueAdapter
end
