# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/activerecord/all/activerecord.rbi
#
# activerecord-7.1.3.2

module ActiveRecord
end
class ActiveRecord::FixtureClassNotFound < ActiveRecord::ActiveRecordError
end
class ActiveRecord::FixtureSet
  extend GlobalID::FixtureSet
end
class ActiveRecord::Fixture
  include Enumerable
end
class ActiveRecord::Fixture::FixtureError < StandardError
end
class ActiveRecord::Fixture::FormatError < ActiveRecord::Fixture::FixtureError
end
