# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/addressable/all/addressable.rbi
#
# addressable-2.8.6

module Addressable
end
class Addressable::Template
end
class Addressable::Template::InvalidTemplateValueError < StandardError
end
class Addressable::Template::InvalidTemplateOperatorError < StandardError
end
class Addressable::Template::TemplateOperatorAbortedError < StandardError
end
class Addressable::Template::MatchData
end
