# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/bootsnap/all/bootsnap.rbi
#
# bootsnap-1.18.3

class Bootsnap::CompileCache::YAML::NoTagsVisitor < Psych::Visitors::NoAliasRuby
  def visit(target); end
end
