# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/capybara/all/capybara.rbi
#
# capybara-3.40.0

module Capybara
end
class Capybara::CapybaraError < StandardError
end
class Capybara::DriverNotFoundError < Capybara::CapybaraError
end
class Capybara::FrozenInTime < Capybara::CapybaraError
end
class Capybara::ElementNotFound < Capybara::CapybaraError
end
class Capybara::ModalNotFound < Capybara::CapybaraError
end
class Capybara::Ambiguous < Capybara::ElementNotFound
end
class Capybara::ExpectationNotMet < Capybara::ElementNotFound
end
class Capybara::FileNotFound < Capybara::CapybaraError
end
class Capybara::UnselectNotAllowed < Capybara::CapybaraError
end
class Capybara::NotSupportedByDriverError < Capybara::CapybaraError
end
class Capybara::InfiniteRedirectError < Capybara::CapybaraError
end
class Capybara::ScopeError < Capybara::CapybaraError
end
class Capybara::WindowError < Capybara::CapybaraError
end
class Capybara::ReadOnlyElementError < Capybara::CapybaraError
end
module Capybara::Driver
end
module Capybara::RackTest
end
module Capybara::Selenium
end
