# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/crass/all/crass.rbi
#
# crass-1.0.6

module Crass
  def self.parse(input, options = nil); end
  def self.parse_properties(input, options = nil); end
end
