# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/drb/all/drb.rbi
#
# drb-2.2.1

module DRb
end
class DRb::DRbUNIXSocket < DRb::DRbTCPSocket
end
