# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/e2mmap/all/e2mmap.rbi
#
# e2mmap-0.1.0

module Exception2MessageMapper
end
class Exception2MessageMapper::ErrNotRegisteredException < StandardError
end
