# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/hotwire-livereload/all/hotwire-livereload.rbi
#
# hotwire-livereload-1.3.1

module Hotwire
end
module Hotwire::Livereload
end
