# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: false
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/jbuilder/all/jbuilder.rbi
#
# jbuilder-2.11.5

class Jbuilder < ActiveSupport::ProxyObject
end
module Jbuilder::DependencyTrackerMethods
end
class Jbuilder::DependencyTracker < ActionView::DependencyTracker::ERBTracker
  include Jbuilder::DependencyTrackerMethods
end
