# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: false
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/kramdown/all/kramdown.rbi
#
# kramdown-2.4.0

module Kramdown
end
module Kramdown::Parser
end
class Kramdown::Parser::Kramdown < Kramdown::Parser::Base
  include Kramdown
end
