# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: false
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/language_server-protocol/all/language_server-protocol.rbi
#
# language_server-protocol-3.17.0.3

module LanguageServer
end
module LanguageServer::Protocol
end
module LanguageServer::Protocol::Transport
end
module LanguageServer::Protocol::Transport::Stdio
end
class LanguageServer::Protocol::Transport::Stdio::Writer < LanguageServer::Protocol::Transport::Io::Writer
end
