# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/loofah/all/loofah.rbi
#
# loofah-2.22.0

module Loofah
  def self.document(*args, &block); end
  def self.fragment(*args, &block); end
  def self.html4_document(*args, &block); end
  def self.html4_fragment(*args, &block); end
  def self.html5_document(*args, &block); end
  def self.html5_fragment(*args, &block); end
  def self.html5_support?; end
  def self.remove_extraneous_whitespace(string); end
  def self.scrub_document(string_or_io, method); end
  def self.scrub_fragment(string_or_io, method); end
  def self.scrub_html4_document(string_or_io, method); end
  def self.scrub_html4_fragment(string_or_io, method); end
  def self.scrub_html5_document(string_or_io, method); end
  def self.scrub_html5_fragment(string_or_io, method); end
  def self.scrub_xml_document(string_or_io, method); end
  def self.scrub_xml_fragment(string_or_io, method); end
  def self.xml_document(*args, &block); end
  def self.xml_fragment(*args, &block); end
end
