# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/matrix/all/matrix.rbi
#
# matrix-0.4.2

module ExceptionForMatrix
end
class ExceptionForMatrix::ErrDimensionMismatch < StandardError
end
class ExceptionForMatrix::ErrNotRegular < StandardError
end
class ExceptionForMatrix::ErrOperationNotDefined < StandardError
end
class ExceptionForMatrix::ErrOperationNotImplemented < StandardError
end
class Matrix
  extend Matrix::ConversionHelper
  include Enumerable
  include ExceptionForMatrix
  include Matrix::CoercionHelper
end
module Matrix::ConversionHelper
end
module Matrix::CoercionHelper
end
class Matrix::Scalar < Numeric
  include ExceptionForMatrix
  include Matrix::CoercionHelper
end
class Vector
  extend Matrix::ConversionHelper
  include Enumerable
  include ExceptionForMatrix
  include Matrix::CoercionHelper
end
class Vector::ZeroVectorError < StandardError
end
