# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: false
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/minitest/all/minitest.rbi
#
# minitest-5.22.3

module Minitest
end
class Minitest::Runnable
end
module Minitest::Reportable
end
class Minitest::Result < Minitest::Runnable
  include Minitest::Reportable
end
class Minitest::AbstractReporter
end
class Minitest::Reporter < Minitest::AbstractReporter
end
class Minitest::ProgressReporter < Minitest::Reporter
end
class Minitest::StatisticsReporter < Minitest::Reporter
end
class Minitest::SummaryReporter < Minitest::StatisticsReporter
end
class Minitest::CompositeReporter < Minitest::AbstractReporter
end
class Minitest::Assertion < Exception
end
class Minitest::Skip < Minitest::Assertion
end
class Minitest::UnexpectedError < Minitest::Assertion
  include Minitest::Compress
end
module Minitest::Guard
end
class Minitest::BacktraceFilter
end
