# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: false
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/msgpack/all/msgpack.rbi
#
# msgpack-1.7.2

module MessagePack
  def dump(v, io = nil, options = nil); end
  def load(src, param = nil); end
  def pack(v, io = nil, options = nil); end
  def self.dump(v, io = nil, options = nil); end
  def self.load(src, param = nil); end
  def self.pack(v, io = nil, options = nil); end
  def self.unpack(src, param = nil); end
  def unpack(src, param = nil); end
end
