# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/nokogiri/all/nokogiri.rbi
#
# nokogiri-1.16.3

module Nokogiri
  def self.Slop(*args, &block); end
  def self.install_default_aliases; end
  def self.make(input = nil, opts = nil, &blk); end
  def self.parse(string, url = nil, encoding = nil, options = nil); end
end
class Object < BasicObject
  def Nokogiri(*args, &block); end
end
