# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: false
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/parser/all/parser.rbi
#
# parser-3.3.0.5

module Parser
end
class Parser::Ruby24 < Parser::Base
end
