# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/polyfill/all/polyfill.rbi
#
# polyfill-1.9.0

module Polyfill
  def get(module_name, methods, options = nil); end
  def self.get(module_name, methods, options = nil); end
end
module Polyfill::Module
end
class Object < BasicObject
  def Polyfill(options = nil); end
end
