# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: false
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/rack-test/all/rack-test.rbi
#
# rack-test-2.1.0

module Rack
end
module Rack::Test
  def self.encoding_aware_strings?; end
end
class Rack::Test::Error < StandardError
end
class Rack::Test::Session
  def after_request(&block); end
  def append_query_params(query_array, query_params); end
  def authorize(username, password); end
  def basic_authorize(username, password); end
  def clear_cookies; end
  def close_body(body); end
  def cookie_jar; end
  def cookie_jar=(arg0); end
  def custom_request(verb, uri, params = nil, env = nil, &block); end
  def default_host; end
  def delete(uri, params = nil, env = nil, &block); end
  def env(name, value); end
  def env_for(uri, env); end
  def follow_redirect!; end
  def get(uri, params = nil, env = nil, &block); end
  def head(uri, params = nil, env = nil, &block); end
  def header(name, value); end
  def initialize(app, default_host = nil); end
  def last_request; end
  def last_response; end
  def multipart_content_type(env); end
  def options(uri, params = nil, env = nil, &block); end
  def parse_uri(path, env); end
  def patch(uri, params = nil, env = nil, &block); end
  def post(uri, params = nil, env = nil, &block); end
  def process_request(uri, env); end
  def put(uri, params = nil, env = nil, &block); end
  def request(uri, env = nil, &block); end
  def restore_state; end
  def self.new(app, default_host = nil); end
  def set_cookie(cookie, uri = nil); end
  extend Forwardable
  include Rack::Test::Utils
end
