# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: false
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/rack-session/all/rack-session.rbi
#
# rack-session-2.0.0

module Rack
end
module Rack::Session
end
class Rack::Session::Cookie < Rack::Session::Abstract::PersistedSecure
end
class Rack::Session::Cookie::Base64
end
class Rack::Session::Cookie::Base64::Marshal < Rack::Session::Cookie::Base64
end
class Rack::Session::Cookie::Base64::JSON < Rack::Session::Cookie::Base64
end
class Rack::Session::Cookie::Base64::ZipJSON < Rack::Session::Cookie::Base64
end
class Rack::Session::Cookie::Identity
end
class Rack::Session::Cookie::Marshal
end
class Rack::Session::Cookie::SessionId < Anonymous_Delegator_18
end
