# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/rails-dom-testing/all/rails-dom-testing.rbi
#
# rails-dom-testing-2.2.0

module Rails
end
module Rails::Dom
end
module Rails::Dom::Testing
end
class Rails::Dom::Testing::Railtie < Rails::Railtie
end
