# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: false
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/railties/all/railties.rbi
#
# railties-7.1.3.2

class ActiveSupport::TestCase < Minitest::Test
  extend ActiveRecord::TestFixtures::ClassMethods
  include ActiveRecord::TestDatabases
  include ActiveRecord::TestFixtures
end
