# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: false
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/regexp_parser/all/regexp_parser.rbi
#
# regexp_parser-2.9.0

class Regexp::Parser
  include Regexp::Expression
end
class Regexp::Parser::ParserError < Regexp::Parser::Error
end
class Regexp::Parser::UnknownTokenTypeError < Regexp::Parser::ParserError
end
class Regexp::Parser::UnknownTokenError < Regexp::Parser::ParserError
end
