# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: false
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/rubyzip/all/rubyzip.rbi
#
# rubyzip-2.3.2

module Zip
end
module Zip::FileSystem
end
class Zip::FileSystem::ZipFsFile
end
class Zip::FileSystem::ZipFsFile::ZipFsStat
end
class Zip::FileSystem::ZipFsDir
end
class Zip::FileSystem::ZipFsDirIterator
  include Enumerable
end
class Zip::FileSystem::ZipFileNameMapper
  include Enumerable
end
class Zip::File < Zip::CentralDirectory
  include Zip::FileSystem
end
