# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/safe_type/all/safe_type.rbi
#
# safe_type-1.1.1

module SafeType
  def self.coerce!(input, rule); end
  def self.coerce(input, rule, coerce_key = nil); end
end
