# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: false
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/selenium-webdriver/all/selenium-webdriver.rbi
#
# selenium-webdriver-4.10.0

module Selenium
end
module Selenium::WebDriver
end
module Selenium::WebDriver::IE
end
class Selenium::WebDriver::IE::Service < Selenium::WebDriver::Service
end
