# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/smart_properties/all/smart_properties.rbi
#
# smart_properties-1.17.0

module SmartProperties
end
module SmartProperties::ClassMethods
end
module SmartProperties::ModuleMethods
end
