# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/solargraph/all/solargraph.rbi
#
# solargraph-0.50.0

module Solargraph
end
class Solargraph::InvalidOffsetError < RangeError
end
class Solargraph::DiagnosticsError < RuntimeError
end
class Solargraph::FileNotFoundError < RuntimeError
end
class Solargraph::SourceNotAvailableError < StandardError
end
class Solargraph::ComplexTypeError < StandardError
end
class Solargraph::WorkspaceTooLargeError < RuntimeError
end
class Solargraph::BundleNotFoundError < StandardError
end
class Solargraph::InvalidRubocopVersionError < RuntimeError
end
