# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: false
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/sprockets-rails/all/sprockets-rails.rbi
#
# sprockets-rails-3.4.2

module Rails
end
class Rails::Application < Rails::Engine
  def asset_precompiled?(logical_path); end
  def assets_manifest; end
  def assets_manifest=(arg0); end
  def precompiled_assets(clear_cache = nil); end
end
class Rails::Application::Configuration < Rails::Engine::Configuration
end
class Rails::Engine < Rails::Railtie
end
module Sprockets
end
class Sprockets::Railtie < Rails::Railtie
  def build_environment(app, initialized = nil); end
  def self.build_manifest(app); end
  include Sprockets::Rails::Utils
end
class Sprockets::Railtie::ManifestNeededError < StandardError
  def initialize; end
end
class Sprockets::Railtie::OrderedOptions < ActiveSupport::OrderedOptions
  def configure(&block); end
end
