# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/sprockets/all/sprockets.rbi
#
# sprockets-4.2.1

module Sprockets
end
class Sprockets::Cache
end
class Sprockets::Cache::FileStore
end
