# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/turbo-rails/all/turbo-rails.rbi
#
# turbo-rails-2.0.5

module Turbo
end
module Turbo::TestAssertions
end
module Turbo::TestAssertions::IntegrationTestAssertions
end
