# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: false
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/xpath/all/xpath.rbi
#
# xpath-3.2.0

module XPath
  extend XPath::DSL
  include XPath::DSL
end
